version: "3.9"

services:
  web: 
    build: .
    container_name: "django_app"
    command: python manage.py runserver 0.0.0.0:8034
    volumes:
      - .:/app
    ports:
      - "8034:8034"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5433"